### PR TITLE
chore: update fastify-compress to match fastify version

### PR DESCRIPTION
**Pull request by AlexisNo**
* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

Update `fastify-compress` to `3.3.0` because it breaks the build with `fastify` version `3.1.1` introduced by commit [29e4d69](https://github.com/Sanofi-IADC/whispr/commit/29e4d69e2a2446fe2d8dfecac8acbce6bb359859#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R34) 

* **What is the current behavior?** (You can also link to an open issue here)

[Broken build](https://github.com/Sanofi-IADC/whispr/runs/1020142705#step:8:173) because of TypeScript error

* **What is the new behavior (if this is a feature change)?**

Build fixed

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

No

* **Other information**:

### CODE REVIEW

**Comment by MeStrak** [comment]
@AlexisNo can you have a look at this PR? https://github.com/Sanofi-IADC/whispr/pull/78

This dependency was previously updated then reverted because it broke file uploads. Since them some more tests have been added but I think this part should be checked specifically.

**Comment by MeStrak** [comment]
@AlexisNo I think you can test this with @David-Wennemaring to make sure it works ok after the update

**Comment by David-Wennemaring** [comment]
Also there is currently a problem with fastify v3 and apollo-server: https://github.com/apollographql/apollo-server/pull/4356

As soon as apollo-server v3 is released, we can update this dependency as well.

**Comment by MeStrak** [comment]
Closing this PR until there is proper support for Fastify v3 in Apollo

**Pull request closed without merging**
