### PR TITLE
Add sort and limit options to whisps graphql query

### PR DESCRIPTION
**Pull request by JeremieMarniquet**

### CODE REVIEW

**Comment by MeStrak** [comment]
Hi @JeremieMarniquet, docs need to be updated with this PR :)

Can you also look at the subscription part again please? It was nice before that the same filter could be used in both subscription and query. Now we saved some lines of code in the back but created more in the front for the two filter types.

The basic approach is nice though, and should be faster as you said but we should be consistent where we can or usage of the API will be confusing.

What if they have the same filter input but
- either the subscription builds the json structure required
- or the query takes the original filter and converts to json object you use
?

The first option for converting it in the subscription endpoint might be executed less frequently so a lower performance impact.

What do you think?

**Comment by JeremieMarniquet** [comment]
Hello James,

Here is what I managed to do :
- The whisps functions still uses the mongoose filter directly
- The Subscriptions filter is now similar to the mongoose filter, except it doesn’t have all the extra options like $ne (Matches all values that are not equal to a specified value.) listed here : https://docs.mongodb.com/manual/reference/operator/query-comparison/

So the right way to filter on nested value is like this  : 
```
{
  "filter": { "data.att1": "value1" }
}
```

One thing to note on array filters :

Consider this object :
```
{ att1: "value1" }
```

This filter will work both in mongoose and our custom filter :
```
{
  "filter": { "att1": ["value1", "value2"] }
}
```
-> object returned

But the following syntax also works for mongoose :
```
{
  "filter": { "att1": {  "$in": ["value1", "value2"] } }
}
```
-> object returned

What do you think ? (I'll update the documentation if it's ok for you)

**Comment by MeStrak** [comment]
@JeremieMarniquet looks really good to me. I think that this adds a lot of power to our filtering which is something that was requested by the team, and now the syntax is consistent between both end points.

@David-Wennemaring @schroedermaxi can you review this PR?

**Comment by schroedermaxi** [comment]
@JeremieMarniquet yes, this really looks good. Definitely some functionalities that we could use really well.

**Comment by JeremieMarniquet** [comment]
@schroedermaxi @MeStrak Perfect thanks :)

I updated the documentation, you can review it if you want !

**Comment by David-Wennemaring** [comment]
@JeremieMarniquet 
Looks good!   
Just one question:
Can you maybe give a positive example for the "Filter on object" as well?
For me it is not clear when this filter would work.

**Comment by JeremieMarniquet** [comment]
@David-Wennemaring Thanks I added an example ! Tell me if it's not clear

**Pull request merged**
