### PR TITLE
fix(gql-fileupload): Fixed failing File-Uploads via GQL

### PR DESCRIPTION
**Pull request by David-Wennemaring**
Removed global validation pipe and readded them to REST-APIs

* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Bugfix for File-Uploads via Graphql where the Validation Pipe breaks the promise of a file.

* **What is the current behavior?** (You can also link to an open issue here)
File-Uploads via Graphql result in an error.

* **What is the new behavior (if this is a feature change)?**
Graphql-Requests no longer pass the Validation pipe.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No

* **Other information**:
Files now have their own field in property on top level of a whisp. 
Only files in the attachment attribute will be uploaded to S3. Any other files will appear as empty objects.
See updated documentation for more details.
```json
{
   "attachments":[{
      "dataMappingPath": "<file location inside the whisp>",
      "file": "S3-Key"
    }]
}
```

### CODE REVIEW

**Comment by MeStrak** [comment]
@David-Wennemaring do you think that it could be a more elegant solution to separate the file upload field from the main data, and @Exclude only that field?

**Comment by Babbafett** [comment]
Agree to @MeStrak we should avoid using this validation pipe for each new rest endpoint, because that's a bit risky and could be avoided by setting it as a global pipe.
In my opinion and as a proposal we could think about introducing "file whisps" which are connected to normal whisps. As files are optional those file whips are optional as well and a general file service could lookup in our whisps whether we have connected file whisps for a whip or not.
In addition with complete separation of whisps and file whisps we gain more flexbility for additional specific queries in the future.

Regarding the unit test of validation pipes to check if the exception handling id working properly we should be able to implement negative unit tests accordingly.

**Comment by David-Wennemaring** [comment]
@MeStrak @Babbafett 
The problem we are facing is this: [https://github.com/typestack/class-transformer/issues/261](https://github.com/typestack/class-transformer/issues/261)

I'm not sure how the @Exclude decorator behaves with the whitelisting option. Could we set it for the data attribute?

What I like about the current solution is:
1. We can upload a file inside a Whisp which results in a single API-Call.
2. We have a url (or at least part of it) in the location where the file was prior. That makes it very simple to include it in (for example) an img-Tag.

Both of these points keep the logic of the Frontend Implementation very simple. One call to create a whisp, one call to get the whisp with url already in the correct place.

Additionally I'm a bit concerned how fast we can implement the File-Whisps or another solution. We would like to do the switch to this Version of Whispr as soon as possible.

**Comment by MeStrak** [comment]
> @MeStrak @Babbafett
> The problem we are facing is this: [typestack/class-transformer#261](https://github.com/typestack/class-transformer/issues/261)
> 
> I'm not sure how the @exclude decorator behaves with the whitelisting option. Could we set it for the data attribute?
> 
> What I like about the current solution is:
> 
> 1. We can upload a file inside a Whisp which results in a single API-Call.
> 2. We have a url (or at least part of it) in the location where the file was prior. That makes it very simple to include it in (for example) an img-Tag.

I'm not sure that we really need to separate it into a completely new object, if the files are only linked to a single whisp. My proposal was more to extract it into a new object within the whisp.

So you would have something equivalent to the following (although I haven't tried codiing it up).

data: { ... } 

@Exclude
files: { ... }

**Comment by David-Wennemaring** [comment]
The first tests with @Exclude were not successfull. It simply removes the property from the request.
But I found a validator @ValidatePromise which might work when we have typesafty in the files Object

**Comment by David-Wennemaring** [comment]
@MeStrak @Babbafett 
Changes made according to our discussions:
A whisp now has a top level field to add attachments:

- When uploading a whisp with a file: **data.attachments.file** can contain a string (for old files) or a binary (for new files)
- A new file is uploaded to S3 and is replaced by its S3 key (<readableID>/<path>/<filename>)

The path is the location inside the whisp where the file is related to.
i.e.: 
```
...,
attachments:[{
   path: "data.comments.attachments.files.0"
   file: "MS-Whisp-1/data.comments.attachments.files.0/comment1.jpg"
}]
```

Please let me know if these changes can be merged.

**Pull request merged**
